export const siteConfig = {
  name: 'SAID Studio',
  fullName: 'Satwika Architecture & Interior Design',
  tagline: 'Spaces designed to belong.',
  contactEmail: 'satwikaarchitects@gmail.com',
  contactPhone: '+91 99080 01558',
  location: 'Block 21, F-1, Vignanpuri Colony, Vidya Nagar, Hyderabad - 44',
  instagram: 'https://instagram.com/saidsays_',
  youtube: 'https://youtube.com/@ArchitectsandInteriorDesigners',

  // Centralized Image Configuration (Easy for replacement)
  assets: {
    hero: {
      main: '/images/courtyard-residence.png',
      alt: 'Luxury Architectural Residence Entrance',
    },
    featuredProject: {
      image: '/images/hero-interior.png',
      title: 'ERA RESIDENCE',
      meta: 'PRIVATE RESIDENCE · GOA / INDIA · 2026',
      alt: 'Era Residence Living Space',
    },
    projectStory: {
      image: '/images/kitchen-detail.png',
      title: 'A RESIDENCE DESIGNED AROUND LIGHT',
      alt: 'Custom Kitchen and Material Detail',
    },
    fullBleed: {
      image: '/images/courtyard-residence.png',
      title: 'THE COAST',
      subtitle: 'PRIVATE RESIDENCE · VIZAG',
      alt: 'Coastal Architecture View',
    },
    collage: [
      { src: '/images/hero-interior.png', alt: 'Living Room Architecture', aspect: '4/3' },
      { src: '/images/kitchen-detail.png', alt: 'Material and Joinery Detail', aspect: '4/5' },
      { src: '/images/courtyard-residence.png', alt: 'Interior Courtyard Light', aspect: '16/10' },
    ],
    about: {
      image: '/images/hero-interior.png',
      alt: 'SAID Studio Interior Space',
    },
    frames: {
      prefix: '/frames/frame_',
      extension: '.jpg',
      totalFrames: 90,
      digits: 3,
    },
  },

  projects: [
    {
      id: '01',
      title: 'Sri BioAesthetics Laboratory & Office',
      category: 'Commercial',
      meta: 'Hyderabad · Commercial Fit-Out & Office · 2026',
      image: '/images/sri-bio/sri-bio-1.jpg',
      widthClass: 'col-span-12 lg:col-span-7',
      aspectRatio: 'aspect-[16/10]',
      slug: 'sri-bioaesthetics',
      website: 'https://sribioaesthetics.com/',
    },
    {
      id: '02',
      title: 'Vijay RV’s Sai Vanamali (3 Flat Interiors)',
      category: 'Residential',
      meta: 'Miyapur, Hyderabad · 3 Residential Flats · 2026',
      image: '/images/sai-vanamali/sai-vanamali-1.jpg',
      widthClass: 'col-span-12 lg:col-span-5',
      aspectRatio: 'aspect-[4/3]',
      slug: 'sai-vanamali-miyapur',
    },
    {
      id: '03',
      title: 'Mukunda Nilayam (3D Architectural Renders)',
      category: 'Residential',
      meta: 'Hyderabad · Luxury Residence Renders · 2026',
      image: '/images/mukunda-nilayam/mukunda-1.jpg',
      widthClass: 'col-span-12 lg:col-span-6',
      aspectRatio: 'aspect-[16/10]',
      slug: 'mukunda-nilayam',
    },
    {
      id: '04',
      title: 'The Courtyard Residence',
      category: 'Residential',
      meta: 'Jubilee Hills, Hyderabad · Residential Villa · 2026',
      image: '/images/courtyard-residence.png',
      widthClass: 'col-span-12 lg:col-span-6',
      aspectRatio: 'aspect-[16/10]',
      slug: 'the-courtyard-residence',
    },
    {
      id: '05',
      title: 'The Walnut Office',
      category: 'Commercial',
      meta: 'Hyderabad · Executive Commercial · 2026',
      image: '/images/walnut/walnut_1.jpg',
      widthClass: 'col-span-12 lg:col-span-4',
      aspectRatio: 'aspect-[4/5]',
      slug: 'the-walnut-office',
    },
    {
      id: '06',
      title: 'The Stone Kitchen',
      category: 'Residential',
      meta: 'Vizag · Custom Kitchen & Dining · 2026',
      image: '/images/kitchen-detail.png',
      widthClass: 'col-span-12 lg:col-span-8',
      aspectRatio: 'aspect-[4/3]',
      slug: 'the-stone-kitchen',
    },
  ],

  services: [
    { id: '01', title: 'Interior Architecture', slug: 'interior-architecture', desc: 'Comprehensive residential and commercial spatial planning, structural interior concepts, circulation flow and architectural documentation.' },
    { id: '02', title: 'Interior Fit-Out', slug: 'interior-fit-out', desc: 'Civil & MEP coordination, precision joinery, custom finish execution, site management and exacting quality control.' },
    { id: '03', title: 'Turnkey Interiors', slug: 'turnkey-interiors', desc: 'Single-point accountability from initial sketch to procurement, execution, final interior styling and white-glove handover.' },
    { id: '04', title: '3D Visualization', slug: '3d-visualization', desc: 'Photorealistic 3D interior renders, material tactile previews, daylight orientation studies and interactive walkthrough scenes.' },
    { id: '05', title: 'Custom Furniture', slug: 'custom-furniture', desc: 'Handcrafted bespoke furniture, custom wardrobes, entertainment units, shop drawings and master artisan woodworking.' },
    { id: '06', title: 'Modular Kitchens', slug: 'modular-kitchens', desc: 'Ergonomic culinary workflow design, premium quartz countertops, moisture-resistant cabinetry and German soft-close hardware.' },
  ],

  processSteps: [
    { no: '01', title: 'DISCOVER', copy: 'Understanding brief, rhythms, light orientation, and lifestyle.' },
    { no: '02', title: 'DEFINE', copy: 'Spatial flow diagrams, material boards, and architectural vision.' },
    { no: '03', title: 'DESIGN', copy: 'Precision 3D modeling, lighting plans, and bespoke furniture details.' },
    { no: '04', title: 'DETAIL', copy: 'Exacting material sourcing, custom joinery, and technical specifications.' },
    { no: '05', title: 'DELIVER', copy: 'One calm, accountable team managing execution to final handover.' },
  ],

  testimonial: {
    quote: '“EVERY DETAIL FELT INTENTIONAL AND CRAFTED AROUND THE WAY WE LIVE.”',
    author: 'Private Residence Client',
    location: 'Hyderabad',
  },
} as const
